/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.components;

/**
 *
 * @author dell
 */
public class ListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ListPanel
     */
    public ListPanel() {
        initComponents();
        tblList.setIndex(-1);
    }

    public String getHandler() {
        return tblList.getHandler();
    }
    
    public void setHandler(String s) {
        tblList.setHandler(s);
        tblList.setId(s);
        btnMoveFirst.setName(s+".moveFirstPage");
        btnMovePrev.setName(s+".moveBackPage");
        btnMoveNext.setName(s+".moveNextPage");
        btnMoveLast.setName(s+".moveLastPage");
        lblRecordCount.setExpression("Page #{" + s + ".pageIndex"  +"}");
        lblRecordCount.setText("Page #{" + s + ".pageIndex"  +"}");
        lblPageCount.setExpression("of #{" + s + ".pageCount"  +"}");
        lblPageCount.setText("of #{" + s + ".pageCount"  +"}");
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblList = new com.rameses.rcp.control.XDataTable();
        jToolBar2 = new javax.swing.JToolBar();
        btnMoveFirst = new com.rameses.rcp.control.XButton();
        btnMovePrev = new com.rameses.rcp.control.XButton();
        btnMoveNext = new com.rameses.rcp.control.XButton();
        btnMoveLast = new com.rameses.rcp.control.XButton();
        jPanel5 = new javax.swing.JPanel();
        lblRecordCount = new com.rameses.rcp.control.XLabel();
        lblPageCount = new com.rameses.rcp.control.XLabel();

        setLayout(new java.awt.BorderLayout());

        tblList.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        tblList.setHandler("listHandler");
        tblList.setName("selectedItem"); // NOI18N
        add(tblList, java.awt.BorderLayout.CENTER);

        jToolBar2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar2.setRollover(true);

        btnMoveFirst.setFocusable(false);
        btnMoveFirst.setIconResource("images/navbar/first.png");
        btnMoveFirst.setName("listHandler.moveFirstPage"); // NOI18N
        jToolBar2.add(btnMoveFirst);

        btnMovePrev.setFocusable(false);
        btnMovePrev.setIconResource("images/navbar/previous.png");
        btnMovePrev.setName("listHandler.moveBackPage"); // NOI18N
        jToolBar2.add(btnMovePrev);

        btnMoveNext.setFocusable(false);
        btnMoveNext.setIconResource("images/navbar/next.png");
        btnMoveNext.setImmediate(true);
        btnMoveNext.setName("listHandler.moveNextPage"); // NOI18N
        jToolBar2.add(btnMoveNext);

        btnMoveLast.setFocusable(false);
        btnMoveLast.setIconResource("images/navbar/last.png");
        btnMoveLast.setName("listHandler.moveLastPage"); // NOI18N
        jToolBar2.add(btnMoveLast);

        jPanel5.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel5.setLayout(new com.rameses.rcp.control.layout.XLayout());

        lblRecordCount.setDepends(new String[] {"selectedItem"});
        lblRecordCount.setExpression("#{recordCountInfo}");
        lblRecordCount.setUseHtml(true);
        jPanel5.add(lblRecordCount);

        lblPageCount.setDepends(new String[] {"selectedItem"});
        lblPageCount.setExpression("#{pageCountInfo}");
        lblPageCount.setUseHtml(true);
        jPanel5.add(lblPageCount);

        jToolBar2.add(jPanel5);

        add(jToolBar2, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton btnMoveFirst;
    private com.rameses.rcp.control.XButton btnMoveLast;
    private com.rameses.rcp.control.XButton btnMoveNext;
    private com.rameses.rcp.control.XButton btnMovePrev;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JToolBar jToolBar2;
    private com.rameses.rcp.control.XLabel lblPageCount;
    private com.rameses.rcp.control.XLabel lblRecordCount;
    private com.rameses.rcp.control.XDataTable tblList;
    // End of variables declaration//GEN-END:variables
}
