/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package templates;

/**
 *
 * @author dell
 */
public class JFXSamplePage extends javax.swing.JPanel {

    /**
     * Creates new form JFXSamplePage
     */
    public JFXSamplePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        browserPanel1 = new templates.BrowserPanel();
        browserPanel2 = new templates.BrowserPanel();

        javax.swing.GroupLayout browserPanel1Layout = new javax.swing.GroupLayout(browserPanel1);
        browserPanel1.setLayout(browserPanel1Layout);
        browserPanel1Layout.setHorizontalGroup(
            browserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        browserPanel1Layout.setVerticalGroup(
            browserPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        browserPanel2.setBackground(new java.awt.Color(51, 51, 255));
        browserPanel2.setUrl("www.google.com");

        javax.swing.GroupLayout browserPanel2Layout = new javax.swing.GroupLayout(browserPanel2);
        browserPanel2.setLayout(browserPanel2Layout);
        browserPanel2Layout.setHorizontalGroup(
            browserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );
        browserPanel2Layout.setVerticalGroup(
            browserPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(browserPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(browserPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private templates.BrowserPanel browserPanel1;
    private templates.BrowserPanel browserPanel2;
    // End of variables declaration//GEN-END:variables
}
