import javax.swing.JDialog;
/*
 * TestPanel2.java
 *
 * Created on May 7, 2013, 11:49 AM
 */

/**
 *
 * @author  compaq
 */
public class TestPanel2 extends javax.swing.JPanel {
    
    /** Creates new form TestPanel2 */
    public TestPanel2() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        jButton1 = new javax.swing.JButton();
        iconedTextField1 = new com.rameses.rcp.control.text.IconedTextField();

        xDecimalField1.setText("xDecimalField1");

        jButton1.setText("jButton1");

        iconedTextField1.setText("iconedTextField1");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(xDecimalField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                    .add(jButton1)
                    .add(iconedTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(251, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(xDecimalField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(jButton1)
                .add(31, 31, 31)
                .add(iconedTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.text.IconedTextField iconedTextField1;
    private javax.swing.JButton jButton1;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    // End of variables declaration//GEN-END:variables
    
}
