/*
 * PhotoForm.java
 *
 * Created on April 22, 2014, 7:15 AM
 */

package com.rameses.osiris2.common.ui;

/**
 *
 * @author  Elmo
 */
public class PhotoComponent extends javax.swing.JPanel {
    
    /** Creates new form PhotoForm */
    public PhotoComponent() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xPhoto1 = new com.rameses.rcp.control.XPhoto();
        jPanel1 = new javax.swing.JPanel();
        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton3 = new com.rameses.rcp.control.XButton();

        xPhoto1.setName("photo");
        xPhoto1.setText("xPhoto1");

        xButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/clip.png")));
        xButton1.setText("Add File");
        xButton1.setCaptionFont(new java.awt.Font("Arial", 0, 10));
        xButton1.setFont(new java.awt.Font("Tahoma", 0, 10));
        xButton1.setMargin(new java.awt.Insets(2, 4, 2, 4));
        xButton1.setName("capture");
        xButton1.setVisibleWhen("#{photo==null && allowCapture==true}");
        jPanel1.add(xButton1);

        xButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/camera.png")));
        xButton2.setText("Add Photo");
        xButton2.setCaptionFont(new java.awt.Font("Arial", 0, 10));
        xButton2.setFont(new java.awt.Font("Tahoma", 0, 10));
        xButton2.setMargin(new java.awt.Insets(2, 4, 2, 4));
        xButton2.setName("camera");
        xButton2.setVisibleWhen("#{photo==null && allowCamera==true}");
        jPanel1.add(xButton2);

        xButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit.png")));
        xButton3.setCaptionFont(new java.awt.Font("Arial", 0, 10));
        xButton3.setFont(new java.awt.Font("Tahoma", 0, 10));
        xButton3.setMargin(new java.awt.Insets(2, 4, 2, 4));
        xButton3.setName("changePhoto");
        xButton3.setText("Change");
        xButton3.setVisibleWhen("#{photo!=null && allowChange==true}");
        jPanel1.add(xButton3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, 0, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(xPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(xPhoto1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XPhoto xPhoto1;
    // End of variables declaration//GEN-END:variables
    
}
