/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.views;


/**
 *
 * @author dell
 */
public class CrudFormPage extends javax.swing.JPanel {

    /**
     * Creates new form CrudFormPage
     */
    public CrudFormPage() {
        initComponents();
        btnSave.setToolTipText("Save");
        btnCreate.setToolTipText("New");
        btnEdit.setToolTipText("Edit");
        btnUndo.setToolTipText("Undo");
        btnCancel.setToolTipText("Cancel Edit");
        
        btnInfo.setToolTipText("Info");
        btnDebug.setToolTipText("Debug Info");
        btnHelp.setToolTipText("Help");
        
        //hide the status panel for now 
        pnlstat.setVisible(false); 
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xStyleRule1 = new com.rameses.rcp.control.XStyleRule();
        pnlstat = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        jToolBar3 = new javax.swing.JToolBar();
        btnDebug = new com.rameses.rcp.control.XButton();
        btnHelp = new com.rameses.rcp.control.XButton();
        btnInfo = new com.rameses.rcp.control.XButton();
        jToolBar1 = new javax.swing.JToolBar();
        btnCancel1 = new com.rameses.rcp.control.XButton();
        btnCreate = new com.rameses.rcp.control.XButton();
        btnEdit = new com.rameses.rcp.control.XButton();
        btnSave = new com.rameses.rcp.control.XButton();
        btnUndo = new com.rameses.rcp.control.XButton();
        btnCancel = new com.rameses.rcp.control.XButton();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        xActionBar2 = new com.rameses.rcp.control.XActionBar();
        btnUp = new com.rameses.rcp.control.XButton();
        btnDown = new com.rameses.rcp.control.XButton();

        setLayout(new java.awt.BorderLayout());

        xStyleRule1.setName("styleRules"); // NOI18N

        javax.swing.GroupLayout xStyleRule1Layout = new javax.swing.GroupLayout(xStyleRule1);
        xStyleRule1.setLayout(xStyleRule1Layout);
        xStyleRule1Layout.setHorizontalGroup(
            xStyleRule1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        xStyleRule1Layout.setVerticalGroup(
            xStyleRule1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        add(xStyleRule1, java.awt.BorderLayout.LINE_START);

        pnlstat.setPreferredSize(new java.awt.Dimension(400, 25));

        javax.swing.GroupLayout pnlstatLayout = new javax.swing.GroupLayout(pnlstat);
        pnlstat.setLayout(pnlstatLayout);
        pnlstatLayout.setHorizontalGroup(
            pnlstatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 727, Short.MAX_VALUE)
        );
        pnlstatLayout.setVerticalGroup(
            pnlstatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 25, Short.MAX_VALUE)
        );

        add(pnlstat, java.awt.BorderLayout.PAGE_END);

        jPanel2.setPreferredSize(new java.awt.Dimension(420, 70));
        jPanel2.setLayout(new com.rameses.rcp.control.layout.YLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(420, 35));

        xLabel1.setBackground(new java.awt.Color(255, 255, 255));
        xLabel1.setExpression("#{title}");
        xLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        xLabel1.setOpaque(true);
        xLabel1.setPreferredSize(new java.awt.Dimension(41, 30));

        jToolBar3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jToolBar3.setRollover(true);
        jToolBar3.setOpaque(false);

        btnDebug.setBackground(new java.awt.Color(255, 255, 255));
        btnDebug.setCaption("\\");
            btnDebug.setFocusable(false);
            btnDebug.setIconResource("images/debug.png");
            btnDebug.setImmediate(true);
            btnDebug.setName("showDebugInfo"); // NOI18N
            btnDebug.setOpaque(true);
            btnDebug.setVisibleWhen("#{ canDebug == true }");
            jToolBar3.add(btnDebug);

            btnHelp.setBackground(new java.awt.Color(255, 255, 255));
            btnHelp.setCaption("\\");
                btnHelp.setFocusable(false);
                btnHelp.setIconResource("images/help.png");
                btnHelp.setImmediate(true);
                btnHelp.setName("showHelp"); // NOI18N
                btnHelp.setOpaque(true);
                jToolBar3.add(btnHelp);

                btnInfo.setBackground(new java.awt.Color(255, 255, 255));
                btnInfo.setCaption("");
                btnInfo.setFocusable(false);
                btnInfo.setIconResource("images/info.png");
                btnInfo.setImmediate(true);
                btnInfo.setName("showInfo"); // NOI18N
                btnInfo.setOpaque(true);
                jToolBar3.add(btnInfo);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(xLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );
                jPanel3Layout.setVerticalGroup(
                    jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                jPanel2.add(jPanel3);

                jToolBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
                jToolBar1.setRollover(true);
                jToolBar1.setPreferredSize(new java.awt.Dimension(100, 30));

                btnCancel1.setCaption("");
                btnCancel1.setFocusable(false);
                btnCancel1.setIconResource("images/menu.png");
                btnCancel1.setImmediate(true);
                btnCancel1.setName("showMenu"); // NOI18N
                jToolBar1.add(btnCancel1);

                btnCreate.setAccelerator("ctrl N");
                btnCreate.setCaption("");
                btnCreate.setFocusable(false);
                btnCreate.setIconResource("images/toolbars/create.png");
                btnCreate.setName("create"); // NOI18N
                btnCreate.setVisibleWhen("#{createAllowed}");
                jToolBar1.add(btnCreate);

                btnEdit.setAccelerator("ctrl E");
                btnEdit.setCaption("");
                btnEdit.setFocusable(false);
                btnEdit.setIconResource("images/toolbars/edit.png");
                btnEdit.setName("edit"); // NOI18N
                btnEdit.setVisibleWhen("#{editAllowed}");
                jToolBar1.add(btnEdit);

                btnSave.setAccelerator("ctrl S");
                btnSave.setCaption("");
                btnSave.setFocusable(false);
                btnSave.setIconResource("images/toolbars/save.png");
                btnSave.setName("save"); // NOI18N
                btnSave.setVisibleWhen("#{saveAllowed}");
                jToolBar1.add(btnSave);

                btnUndo.setAccelerator("ctrl U");
                btnUndo.setCaption("");
                btnUndo.setFocusable(false);
                btnUndo.setIconResource("images/toolbars/undo.png");
                btnUndo.setImmediate(true);
                btnUndo.setName("undo"); // NOI18N
                btnUndo.setVisibleWhen("#{undoAllowed}");
                jToolBar1.add(btnUndo);

                btnCancel.setCaption("");
                btnCancel.setFocusable(false);
                btnCancel.setIconResource("images/toolbars/cancel.png");
                btnCancel.setImmediate(true);
                btnCancel.setName("unedit"); // NOI18N
                btnCancel.setVisibleWhen("#{cancelEditAllowed}");
                jToolBar1.add(btnCancel);

                xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 0));
                xActionBar1.setDynamic(true);
                xActionBar1.setName("extActions"); // NOI18N
                jToolBar1.add(xActionBar1);

                xActionBar2.setBorder(null);
                xActionBar2.setName("navActions"); // NOI18N
                xActionBar2.setOrientationHAlignment("RIGHT");
                xActionBar2.setPreferredSize(new java.awt.Dimension(100, 29));
                xActionBar2.setTextPosition("CENTER");
                jToolBar1.add(xActionBar2);

                btnUp.setFocusable(false);
                btnUp.setIconResource("images/toolbars/arrow_up.png");
                btnUp.setImmediate(true);
                btnUp.setName("moveUp"); // NOI18N
                btnUp.setVisibleWhen("#{showNavigation==true}");
                jToolBar1.add(btnUp);

                btnDown.setFocusable(false);
                btnDown.setIconResource("images/toolbars/arrow_down.png");
                btnDown.setImmediate(true);
                btnDown.setName("moveDown"); // NOI18N
                btnDown.setVisibleWhen("#{showNavigation==true}");
                jToolBar1.add(btnDown);

                jPanel2.add(jToolBar1);

                add(jPanel2, java.awt.BorderLayout.NORTH);
            }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton btnCancel;
    private com.rameses.rcp.control.XButton btnCancel1;
    private com.rameses.rcp.control.XButton btnCreate;
    private com.rameses.rcp.control.XButton btnDebug;
    private com.rameses.rcp.control.XButton btnDown;
    private com.rameses.rcp.control.XButton btnEdit;
    private com.rameses.rcp.control.XButton btnHelp;
    private com.rameses.rcp.control.XButton btnInfo;
    private com.rameses.rcp.control.XButton btnSave;
    private com.rameses.rcp.control.XButton btnUndo;
    private com.rameses.rcp.control.XButton btnUp;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JToolBar jToolBar3;
    private javax.swing.JPanel pnlstat;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XActionBar xActionBar2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XStyleRule xStyleRule1;
    // End of variables declaration//GEN-END:variables
}
