/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.views;

import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author dell
 */
@Template(ChangeInfoPage.class)
public class DynamicChangeInfoPage extends javax.swing.JPanel {

    /**
     * Creates new form DynamicChangeInfoPage
     */
    public DynamicChangeInfoPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xFormPanel1 = new com.rameses.rcp.control.XFormPanel();

        setLayout(new java.awt.BorderLayout());

        xFormPanel1.setCaptionWidth(120);
        xFormPanel1.setDynamic(true);
        xFormPanel1.setName("formControls"); // NOI18N
        add(xFormPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XFormPanel xFormPanel1;
    // End of variables declaration//GEN-END:variables
}
