/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.seti2.views;

/**
 *
 * @author dell
 */
public class FilterCriteriaItemPanel extends javax.swing.JPanel {

    /**
     * Creates new form StringCriteria
     */
    public FilterCriteriaItemPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xDateField2 = new com.rameses.rcp.control.XDateField();
        xComboBox2 = new com.rameses.rcp.control.XComboBox();
        xButton1 = new com.rameses.rcp.control.XButton();
        xPanel3 = new com.rameses.rcp.control.XPanel();
        datePanel = new javax.swing.JPanel();
        xDateField1 = new com.rameses.rcp.control.XDateField();
        xLabel1 = new com.rameses.rcp.control.XLabel();
        xDateField3 = new com.rameses.rcp.control.XDateField();
        booleanPanel = new javax.swing.JPanel();
        stringPanel = new javax.swing.JPanel();
        xTextField2 = new com.rameses.rcp.control.XTextField();
        decimalPanel = new javax.swing.JPanel();
        xDecimalField1 = new com.rameses.rcp.control.XDecimalField();
        xDecimalField2 = new com.rameses.rcp.control.XDecimalField();
        integerPanel = new javax.swing.JPanel();
        xIntegerField1 = new com.rameses.rcp.control.XIntegerField();
        xIntegerField2 = new com.rameses.rcp.control.XIntegerField();
        xButton2 = new com.rameses.rcp.control.XButton();
        xComboBox1 = new com.rameses.rcp.control.XComboBox();

        xDateField2.setText("xDateField1");

        xComboBox2.setExpression("#{item.caption}");
        xComboBox2.setItems("fieldList");
        xComboBox2.setName("entry.field"); // NOI18N
        xComboBox2.setShowCaption(false);

        xButton1.setIconResource("images/toolbars/trash.png");
        xButton1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        xButton1.setName("removeField"); // NOI18N
        xButton1.setPreferredSize(new java.awt.Dimension(25, 22));
        xButton1.setVisibleWhen("#{entry.index != 1 }");

        xPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 5, 5));
        xPanel3.setDepends(new String[] {"entry.field"});
        xPanel3.setName("datatype"); // NOI18N
        xPanel3.setPreferredSize(new java.awt.Dimension(214, 30));
        xPanel3.setLayout(new java.awt.CardLayout());

        datePanel.setName("date"); // NOI18N

        xDateField1.setName("entry.value"); // NOI18N

        xLabel1.setDepends(new String[] {"entry.operator"});
        xLabel1.setText("to");
        xLabel1.setVisibleWhen("#{entry?.operator?.key == 'BETWEEN' }");

        xDateField3.setDepends(new String[] {"entry.operator"});
        xDateField3.setName("entry.value2"); // NOI18N
        xDateField3.setVisibleWhen("#{entry?.operator?.key == 'BETWEEN' }");

        javax.swing.GroupLayout datePanelLayout = new javax.swing.GroupLayout(datePanel);
        datePanel.setLayout(datePanelLayout);
        datePanelLayout.setHorizontalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addComponent(xDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xDateField3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        datePanelLayout.setVerticalGroup(
            datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(datePanelLayout.createSequentialGroup()
                .addGroup(datePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xDateField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xDateField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        xPanel3.add(datePanel, "date");

        booleanPanel.setName("boolean"); // NOI18N

        javax.swing.GroupLayout booleanPanelLayout = new javax.swing.GroupLayout(booleanPanel);
        booleanPanel.setLayout(booleanPanelLayout);
        booleanPanelLayout.setHorizontalGroup(
            booleanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 209, Short.MAX_VALUE)
        );
        booleanPanelLayout.setVerticalGroup(
            booleanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 29, Short.MAX_VALUE)
        );

        xPanel3.add(booleanPanel, "boolean");

        xTextField2.setName("entry.value"); // NOI18N
        xTextField2.setTextCase(com.rameses.rcp.constant.TextCase.NONE);

        javax.swing.GroupLayout stringPanelLayout = new javax.swing.GroupLayout(stringPanel);
        stringPanel.setLayout(stringPanelLayout);
        stringPanelLayout.setHorizontalGroup(
            stringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(xTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
        );
        stringPanelLayout.setVerticalGroup(
            stringPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stringPanelLayout.createSequentialGroup()
                .addComponent(xTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        xPanel3.add(stringPanel, "string");

        xDecimalField1.setName("entry.value"); // NOI18N

        xDecimalField2.setName("entry.value2"); // NOI18N
        xDecimalField2.setVisibleWhen("#{entry?.operator?.key == 'BETWEEN' }");

        javax.swing.GroupLayout decimalPanelLayout = new javax.swing.GroupLayout(decimalPanel);
        decimalPanel.setLayout(decimalPanelLayout);
        decimalPanelLayout.setHorizontalGroup(
            decimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decimalPanelLayout.createSequentialGroup()
                .addComponent(xDecimalField1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xDecimalField2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 51, Short.MAX_VALUE))
        );
        decimalPanelLayout.setVerticalGroup(
            decimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(decimalPanelLayout.createSequentialGroup()
                .addGroup(decimalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xDecimalField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xDecimalField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        xPanel3.add(decimalPanel, "decimal");

        xIntegerField1.setName("entry.value"); // NOI18N

        xIntegerField2.setDepends(new String[] {"entry.operator"});
        xIntegerField2.setName("entry.value2"); // NOI18N
        xIntegerField2.setVisibleWhen("#{entry?.operator?.key== 'BETWEEN' }");

        javax.swing.GroupLayout integerPanelLayout = new javax.swing.GroupLayout(integerPanel);
        integerPanel.setLayout(integerPanelLayout);
        integerPanelLayout.setHorizontalGroup(
            integerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integerPanelLayout.createSequentialGroup()
                .addComponent(xIntegerField1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xIntegerField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );
        integerPanelLayout.setVerticalGroup(
            integerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(integerPanelLayout.createSequentialGroup()
                .addGroup(integerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xIntegerField1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xIntegerField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 8, Short.MAX_VALUE))
        );

        xPanel3.add(integerPanel, "integer");

        xButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        xButton2.setForeground(new java.awt.Color(0, 102, 255));
        xButton2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        xButton2.setName("addField"); // NOI18N
        xButton2.setPreferredSize(new java.awt.Dimension(25, 22));
        xButton2.setText("+");
        xButton2.setVisibleWhen("#{entry.index == caller.fieldIndex}");

        xComboBox1.setDepends(new String[] {"entry.field"});
        xComboBox1.setDynamic(true);
        xComboBox1.setExpression("#{item.caption}");
        xComboBox1.setItems("operatorList");
        xComboBox1.setName("entry.operator"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(xComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(xComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(xComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(xButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(xButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(xPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel booleanPanel;
    private javax.swing.JPanel datePanel;
    private javax.swing.JPanel decimalPanel;
    private javax.swing.JPanel integerPanel;
    private javax.swing.JPanel stringPanel;
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XComboBox xComboBox1;
    private com.rameses.rcp.control.XComboBox xComboBox2;
    private com.rameses.rcp.control.XDateField xDateField1;
    private com.rameses.rcp.control.XDateField xDateField2;
    private com.rameses.rcp.control.XDateField xDateField3;
    private com.rameses.rcp.control.XDecimalField xDecimalField1;
    private com.rameses.rcp.control.XDecimalField xDecimalField2;
    private com.rameses.rcp.control.XIntegerField xIntegerField1;
    private com.rameses.rcp.control.XIntegerField xIntegerField2;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XPanel xPanel3;
    private com.rameses.rcp.control.XTextField xTextField2;
    // End of variables declaration//GEN-END:variables
}
