/*
 * RuleMgmtQuery.java
 *
 * Created on September 29, 2013, 4:04 PM
 */

package com.rameses.rulemgmt;

/**
 *
 * @author  Elmo
 */
public class RuleMgmtQuery extends javax.swing.JPanel {
    
    /** Creates new form RuleMgmtQuery */
    public RuleMgmtQuery() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cboRulegroup = new com.rameses.rcp.control.XComboBox();
        jLabel2 = new javax.swing.JLabel();
        cboState = new com.rameses.rcp.control.XComboBox();
        jLabel3 = new javax.swing.JLabel();
        xTextField1 = new com.rameses.rcp.control.XTextField();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 0, 3, 5));
        setLayout(new com.rameses.rcp.control.layout.XLayout());

        jLabel1.setText("Rule Group");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 5));
        add(jLabel1);

        cboRulegroup.setExpression("#{item.title}");
        cboRulegroup.setItemKey("name");
        cboRulegroup.setItems("rulegroups");
        cboRulegroup.setName("query.rulegroup"); // NOI18N
        cboRulegroup.setPreferredSize(new java.awt.Dimension(170, 20));
        add(cboRulegroup);

        jLabel2.setText("State");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 5));
        add(jLabel2);

        cboState.setCaption("Rule State");
        cboState.setItems("rulestates");
        cboState.setName("query.state"); // NOI18N
        cboState.setPreferredSize(new java.awt.Dimension(100, 20));
        add(cboState);

        jLabel3.setText("Title");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 5));
        add(jLabel3);

        xTextField1.setName("query.title"); // NOI18N
        xTextField1.setPreferredSize(new java.awt.Dimension(170, 20));
        add(xTextField1);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XComboBox cboRulegroup;
    private com.rameses.rcp.control.XComboBox cboState;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private com.rameses.rcp.control.XTextField xTextField1;
    // End of variables declaration//GEN-END:variables
    
}
