/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package test.view;

/**
 *
 * @author ramesesinc
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xButton1 = new com.rameses.rcp.control.XButton();
        xButton2 = new com.rameses.rcp.control.XButton();
        xButton3 = new com.rameses.rcp.control.XButton();
        xButton4 = new com.rameses.rcp.control.XButton();
        xButton5 = new com.rameses.rcp.control.XButton();

        setLayout(new java.awt.BorderLayout());

        xButton1.setText("xButton1");
        add(xButton1, java.awt.BorderLayout.PAGE_END);

        xButton2.setText("xButton1");
        add(xButton2, java.awt.BorderLayout.PAGE_START);

        xButton3.setText("xButton1");
        add(xButton3, java.awt.BorderLayout.LINE_START);

        xButton4.setText("xButton1");
        add(xButton4, java.awt.BorderLayout.LINE_END);

        xButton5.setText("xButton1");
        add(xButton5, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XButton xButton1;
    private com.rameses.rcp.control.XButton xButton2;
    private com.rameses.rcp.control.XButton xButton3;
    private com.rameses.rcp.control.XButton xButton4;
    private com.rameses.rcp.control.XButton xButton5;
    // End of variables declaration//GEN-END:variables
}
