/*
 * ExplorerViewListPage.java
 *
 * Created on April 24, 2013, 12:44 PM
 */

package com.rameses.osiris2.themes;

import java.awt.Font;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author  wflores
 */
public class ExplorerViewListPage extends javax.swing.JPanel {
    
    public ExplorerViewListPage() {
        initComponents();
        
        Map props = new HashMap();
        props.put("showTopBorder", true); 
        props.put("showBottomBorder", false); 
        navBar.putClientProperty("Border.properties", props);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        pnlHeader = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblTitle = new com.rameses.rcp.control.XLabel();
        xActionBar1 = new com.rameses.rcp.control.XActionBar();
        xActionBar2 = new com.rameses.rcp.control.XActionBar();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        pnlBody = new javax.swing.JPanel();
        xDataTable1 = new com.rameses.rcp.control.XDataTable();
        navBar = new com.rameses.rcp.control.XActionBar();

        setLayout(new java.awt.BorderLayout());

        pnlHeader.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        com.rameses.rcp.control.border.XEtchedBorder xEtchedBorder1 = new com.rameses.rcp.control.border.XEtchedBorder();
        xEtchedBorder1.setHideBottom(true);
        xEtchedBorder1.setHideRight(true);
        jPanel3.setBorder(xEtchedBorder1);
        lblTitle.setBackground(new java.awt.Color(255, 255, 255));
        lblTitle.setExpression("#{title}");
        lblTitle.setFontStyle("font-size: 16; font-weight:bold;");
        lblTitle.setOpaque(true);
        lblTitle.setPadding(new java.awt.Insets(2, 7, 2, 5));
        jPanel3.add(lblTitle, java.awt.BorderLayout.WEST);

        xActionBar1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xActionBar1.setButtonBorderPainted(false);
        xActionBar1.setButtonContentAreaFilled(false);
        xActionBar1.setDynamic(true);
        xActionBar1.setName("nodeActions");
        xActionBar1.setOpaque(false);
        xActionBar1.setShowCaptions(false);
        xActionBar1.setUseToolBar(false);
        jPanel3.add(xActionBar1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, java.awt.BorderLayout.NORTH);

        com.rameses.rcp.control.border.XEtchedBorder xEtchedBorder2 = new com.rameses.rcp.control.border.XEtchedBorder();
        xEtchedBorder2.setHideRight(true);
        xEtchedBorder2.setPadding(new java.awt.Insets(0, 5, 0, 0));
        xActionBar2.setBorder(xEtchedBorder2);
        xActionBar2.setDepends(new String[] {"selectedEntity"});
        xActionBar2.setDynamic(true);
        xActionBar2.setName("formActions");
        jPanel2.add(xActionBar2, java.awt.BorderLayout.SOUTH);

        pnlHeader.add(jPanel2, java.awt.BorderLayout.NORTH);

        xSubFormPanel1.setHandler("queryForm");
        xSubFormPanel1.setVisibleWhen("#{queryFormVisible == true}");
        org.jdesktop.layout.GroupLayout xSubFormPanel1Layout = new org.jdesktop.layout.GroupLayout(xSubFormPanel1);
        xSubFormPanel1.setLayout(xSubFormPanel1Layout);
        xSubFormPanel1Layout.setHorizontalGroup(
            xSubFormPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 587, Short.MAX_VALUE)
        );
        xSubFormPanel1Layout.setVerticalGroup(
            xSubFormPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 20, Short.MAX_VALUE)
        );
        pnlHeader.add(xSubFormPanel1, java.awt.BorderLayout.SOUTH);

        add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlBody.setLayout(new java.awt.BorderLayout());

        pnlBody.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 0, 0, 2));
        xDataTable1.setHandler("listHandler");
        xDataTable1.setImmediate(true);
        xDataTable1.setName("selectedEntity");
        pnlBody.add(xDataTable1, java.awt.BorderLayout.CENTER);

        add(pnlBody, java.awt.BorderLayout.CENTER);

        navBar.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 5, 0, 0));
        navBar.setName("navActions");
        add(navBar, java.awt.BorderLayout.SOUTH);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private com.rameses.rcp.control.XLabel lblTitle;
    private com.rameses.rcp.control.XActionBar navBar;
    private javax.swing.JPanel pnlBody;
    private javax.swing.JPanel pnlHeader;
    private com.rameses.rcp.control.XActionBar xActionBar1;
    private com.rameses.rcp.control.XActionBar xActionBar2;
    private com.rameses.rcp.control.XDataTable xDataTable1;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    // End of variables declaration//GEN-END:variables
    
}
