/*
 * ExplorerViewContentPage.java
 *
 * Created on July 25, 2013, 5:25 PM
 */

package com.rameses.osiris2.themes;

/**
 *
 * @author  compaq
 */
public class ExplorerViewContentPage extends javax.swing.JPanel {
    
    /** Creates new form ExplorerViewFormPage */
    public ExplorerViewContentPage() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        xDataTable1 = new com.rameses.rcp.control.XDataTable();

        setLayout(new java.awt.BorderLayout());

        xDataTable1.setHandler("listHandler");
        xDataTable1.setName("selectedNode");
        add(xDataTable1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.rameses.rcp.control.XDataTable xDataTable1;
    // End of variables declaration//GEN-END:variables
    
}
