/*
 * ListPage.java
 *
 * Created on April 24, 2013, 12:44 PM
 */

package com.rameses.osiris2.themes;

import java.awt.Font;

/**
 *
 * @author  wflores
 */
public class ExplorerViewPage extends javax.swing.JPanel {
    
    public ExplorerViewPage() {
        initComponents();
        //lblTitle.setFont(Font.decode("-bold-18"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlView = new javax.swing.JPanel();
        xSubFormPanel1 = new com.rameses.rcp.control.XSubFormPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTree1 = new com.rameses.rcp.control.XTree();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel1.setName("header");
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel1.add(jPanel2, java.awt.BorderLayout.NORTH);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jSplitPane1.setDividerLocation(150);
        jSplitPane1.setName("body");
        pnlView.setLayout(new java.awt.BorderLayout());

        pnlView.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xSubFormPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        xSubFormPanel1.setDynamic(true);
        xSubFormPanel1.setHandler("openerObject");
        xSubFormPanel1.setName("subform");
        pnlView.add(xSubFormPanel1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setRightComponent(pnlView);

        com.rameses.rcp.control.border.XLineBorder xLineBorder1 = new com.rameses.rcp.control.border.XLineBorder();
        xLineBorder1.setLineColor(java.awt.SystemColor.controlShadow);
        jScrollPane1.setBorder(xLineBorder1);
        xTree1.setHandler("nodeModel");
        xTree1.setName("selectedNode");
        jScrollPane1.setViewportView(xTree1);

        jSplitPane1.setLeftComponent(jScrollPane1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlView;
    private com.rameses.rcp.control.XSubFormPanel xSubFormPanel1;
    private com.rameses.rcp.control.XTree xTree1;
    // End of variables declaration//GEN-END:variables
    
}
