/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rameses.osiris2.views;

import com.rameses.osiris2.themes.OKCancelPage;
import com.rameses.rcp.ui.annotations.StyleSheet;
import com.rameses.rcp.ui.annotations.Template;

/**
 *
 * @author wflores
 */
@StyleSheet
@Template(OKCancelPage.class)
public class RemarkPage extends javax.swing.JPanel {

    /**
     * Creates new form RemarkPage
     */
    public RemarkPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        xLabel1 = new com.rameses.rcp.control.XLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        xTextArea1 = new com.rameses.rcp.control.XTextArea();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setPreferredSize(new java.awt.Dimension(523, 142));
        setLayout(new java.awt.BorderLayout());

        xLabel1.setExpression("#{label}");
        xLabel1.setVisibleWhen("#{label ? true : false}");
        xLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 10, 0));
        xLabel1.setFontStyle("font-size:12;");
        add(xLabel1, java.awt.BorderLayout.PAGE_START);

        xTextArea1.setLineWrap(true);
        xTextArea1.setName("message"); // NOI18N
        xTextArea1.setWrapStyleWord(true);
        xTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 5, 5));
        xTextArea1.setExitOnTabKey(true);
        xTextArea1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        xTextArea1.setRequired(true);
        jScrollPane1.setViewportView(xTextArea1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.rameses.rcp.control.XLabel xLabel1;
    private com.rameses.rcp.control.XTextArea xTextArea1;
    // End of variables declaration//GEN-END:variables
}
